### ISSUE TITLE
Can you please include a license?

### ISSUE THREAD

**Issue by mathe-e-botond** [tagconcierge/consent-banner-js#4]
This is an awesome little library. Unfortunately I did not find any mention of a license. If a code is posted without any explicit license, it is generally considered to be "All Rights Reserved" by default. This means that the author retains all rights and the code is not free to use, modify, or distribute without the author's explicit permission.

May I recommend MIT license?

**Comment by mfrankiewicz** [comment]
Hello, thanks for your interest and for bringing it to our attention. We have added the MIT license - https://github.com/tagconcierge/consent-banner-js/pull/5.
